In [19]:
import numpy as np

# Define the gridworld
grid = np.zeros((4, 4))
grid[1, 1] = -10
grid[3, 3] = 10

# Define the action space
actions = ["up", "down", "left", "right"]

# Define the transition function
def transition(state, action):
    i, j = state
    if action == "up":
        i = max(i-1, 0)
    elif action == "down":
        i = min(i+1, 3)
    elif action == "left":
        j = max(j-1, 0)
    elif action == "right":
        j = min(j+1, 3)
    if grid[i, j] == -10:
        reward = -10
        next_state = (0, 0)
    elif grid[i, j] == 10:
        reward = 10
        next_state = (0, 0)
    else:
        reward = 0
        next_state = (i, j)
    return next_state, reward

# Define the initial policy (always move right)
policy = np.zeros((4, 4), dtype=np.int)
policy[:, -1] = 1

# Define the discount factor and the maximum number of iterations
gamma = 0.9
max_iterations = 100

# Policy iteration algorithm
for i in range(max_iterations):
    # Policy evaluation
    values = np.zeros((4, 4))
    for k in range(100):
        for state in np.ndindex((4, 4)):
            action = actions[policy[state]]
            next_state, reward = transition(state, action)
            values[state] = reward + gamma * values[next_state]
    # Policy improvement
    policy_stable = True
    for state in np.ndindex((4, 4)):
        old_action = policy[state]
        q_values = []
        for action in actions:
            next_state, reward = transition(state, action)
            q_values.append(reward + gamma * values[next_state])
        policy[state] = np.argmax(q_values)
        if old_action != policy[state]:
            policy_stable = False
    if policy_stable:
        break

# Print the optimal policy and the state values
print("Optimal policy:")
print(policy)
print("State values:")
print(values)


Optimal policy:
[[1 3 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [3 3 3 1]]
State values:
[[12.60217842 14.00246034 15.55828926 17.28698807]
 [14.00246034 15.55828926 17.28698807 19.20776452]
 [15.55828926 17.28698807 19.20776452 21.34196058]
 [17.28698807 19.20776452 21.34196058 21.34196058]]


C:\Users\choud\AppData\Local\Temp\ipykernel_14232\928582895.py:34: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  policy = np.zeros((4, 4), dtype=np.int)
