In [3]:
import gym
import numpy as np

# create the environment
env = gym.make('FrozenLake-v1')

# set the discount factor
gamma = 1

# initialize the policy to a uniform distribution over actions for each state
num_states = env.observation_space.n
num_actions = env.action_space.n
policy = np.ones((num_states, num_actions)) / num_actions

print("Number of States: ", num_states)
print("Number of Actions: ", num_actions)
print("Initaly Policy: \n")
print(policy)
print()

# define the policy evaluation function
def policy_evaluation(policy, env, gamma, theta, V, i):
    while True:
        delta = 0
        # for each state, update the value function
        for s in range(num_states):
            v = V[s]
            # calculate the value of each action in the current state
            q = np.zeros(num_actions)  
            for a in range(num_actions):
                for prob, next_state, reward, done in env.P[s][a]:
                    q[a] += prob * (reward + gamma * V[next_state])
            # update the value of the current state
            V[s] = np.dot(policy[s], q)
            # calculate the maximum change in the value function
            delta = max(delta, abs(v - V[s]))
        # check if the maximum change is below the threshold
        if delta < theta:
            break
    return V

# define the policy improvement function
def policy_improvement(policyy, env, gamma, V, i):
    # initialize the policy to be greedy with respect to the current value function
    new_policy = np.zeros((num_states, num_actions))
    for s in range(num_states):
        # calculate the value of each action in the current state
        q = np.zeros(num_actions)
        for a in range(num_actions):
            for prob, next_state, reward, done in env.P[s][a]:
                q[a] += prob * (reward + gamma * V[next_state])
        # update the policy to choose the action with the highest value
        best_action = np.argmax(q)
        new_policy[s][best_action] = 1
    print(f"Policy: {i}")
    print(new_policy)
    print()
    return new_policy

# perform policy iteration
theta = 1e-8  # threshold for convergence
i = 1
V = np.zeros(num_states)
while True:
    # evaluate the current policy
    V = policy_evaluation(policy, env, gamma, theta, V, i)
    # improve the policy
    new_policy = policy_improvement(policy, env, gamma, V, i)
    i += 1
    # check if the policy has converged
    if np.array_equal(policy, new_policy):
        break
    policy = new_policy

# print the final policy
print("Final Policy: ")
print(policy)

Number of States:  16
Number of Actions:  4
Initaly Policy: 

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]

Policy: 1
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

Policy: 2
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

Policy: 3
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0